name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses5 unzip openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer cython

      - name: Accept Android SDK Licenses
        run: |
          mkdir -p ~/.android
          yes | sdkmanager --licenses || true
          yes | sdkmanager --update
          yes | sdkmanager "platforms;android-33" "build-tools;33.0.2" "platform-tools"

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: InvoiceApp
          path: bin/*.apk
